export interface ProposedTour {
  objectId: string;
  country: string;
  cost: string;
  city: string;
  difficultyLevel: string;
  coverImageUrl: string;
  galleryImageUrls: string[];
  guideId: string;
  description: string;
  tourFeatures: string[];
  cameraZoom: number;
  type: "custom" | "getaway" | "offered";
  meetingPointLat: number;
  otherTourFeature: string;
  meetingPoint: string;
  phone: string;
  countryCode: string;
  name: string;
  meetingPointLong: number;
  tourTimes: string[];
  tourDuration: string;
  isApproved: boolean;
  isNotified: boolean;
  isActive: boolean;
  tourPackages: string[];
  pickupPoints: string[];
  createdAt: string;
  updatedAt: string;
}